# Generated by Django 5.0.2 on 2024-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
